### ISSUE TITLE
NullReferenceException in GraphViewerGdi.Tessellator.TessellateCurve

### ISSUE THREAD

**Issue by bent-rasmussen** [microsoft/automatic-graph-layout#210]
When using MSAGL in a WPF application where the GDIViewer is hosted in a WindowsFormsHost, sometimes, the GDIViewer crashes for an unknown reason. A big red X is drawn across the GDIViewer surface. 

MSAGL Nuget packages used: 

```xml
<package id="Microsoft.Msagl" version="1.1.3" targetFramework="net48" />
<package id="Microsoft.Msagl.Drawing" version="1.1.3" targetFramework="net48" />
<package id="Microsoft.Msagl.GraphViewerGDI" version="1.1.3" targetFramework="net48" />
```

See exception details below.

**Exception:**

```csharp
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Msagl.GraphViewerGdi.Tessellator.TessellateCurve(DEdge dedge, Double radiusForUnderlyingPolylineCorners)
   at Microsoft.Msagl.GraphViewerGdi.DGraph.BuildBBHierarchyUnderDEdge(DEdge dEdge)
   at Microsoft.Msagl.GraphViewerGdi.DGraph.BuildBBHierarchyUnderDObject(DObject dObject)
   at Microsoft.Msagl.GraphViewerGdi.DGraph.BuildBBHierarchy()
   at Microsoft.Msagl.GraphViewerGdi.GViewer.get_BbNode()
   at Microsoft.Msagl.GraphViewerGdi.DrawingPanel.HitIfBbNodeIsNotNull(MouseEventArgs args)
   at Microsoft.Msagl.GraphViewerGdi.DrawingPanel.OnMouseMove(MouseEventArgs args)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
StaticalPrism
    Assembly Version: 0.0.0.0
    Win32 Version: 
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/StaticalPrism.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4018.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
Basis
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/Basis.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
FSharp.Core
    Assembly Version: 4.7.0.0
    Win32 Version: 4.700.19.40208
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/FSharp.Core.DLL
----------------------------------------
log4net
    Assembly Version: 2.0.8.0
    Win32 Version: 2.0.8.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/log4net.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Reflection
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.dll
----------------------------------------
LogicNP.CryptoLicensing
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.0.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/LogicNP.CryptoLicensing.DLL
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
WatermarkBehavior
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/WatermarkBehavior.DLL
----------------------------------------
Controls
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/Controls.DLL
----------------------------------------
System.Windows.Interactivity
    Assembly Version: 4.5.0.0
    Win32 Version: 3.0.30810.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/System.Windows.Interactivity.DLL
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
FileSystem
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/FileSystem.DLL
----------------------------------------
FParsec
    Assembly Version: 0.9.2.0
    Win32 Version: 0.9.2.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/FParsec.DLL
----------------------------------------
FParsecCS
    Assembly Version: 0.9.2.0
    Win32 Version: 0.9.2.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/FParsecCS.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
PresentationFramework-SystemXmlLinq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXmlLinq/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXmlLinq.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
PresentationFramework-SystemCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemCore/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemCore.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
FSharpx.Collections
    Assembly Version: 1.0.0.0
    Win32 Version: 
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/FSharpx.Collections.DLL
----------------------------------------
ALStorage
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/ALStorage.DLL
----------------------------------------
Index
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/Index.DLL
----------------------------------------
System.Reactive
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0.1
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/System.Reactive.DLL
----------------------------------------
Folding
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/Folding.DLL
----------------------------------------
Syntax
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/Syntax.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.Threading.Tasks.Dataflow
    Assembly Version: 4.6.4.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/System.Threading.Tasks.Dataflow.DLL
----------------------------------------
ALParser
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/ALParser.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.2.23222
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Dynamics.Nav.CodeAnalysis
    Assembly Version: 4.0.2.41516
    Win32 Version: 4.0.2.41516
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/Microsoft.Dynamics.Nav.CodeAnalysis.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/System.Collections.Immutable.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.27617.02
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.5.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/System.Numerics.Vectors.DLL
----------------------------------------
Microsoft.CodeAnalysis.CSharp
    Assembly Version: 2.9.0.0
    Win32 Version: 2.9.0.63208
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/Microsoft.CodeAnalysis.CSharp.DLL
----------------------------------------
Microsoft.CodeAnalysis
    Assembly Version: 2.9.0.0
    Win32 Version: 2.9.0.63208
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/Microsoft.CodeAnalysis.DLL
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll
----------------------------------------
System.IO
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.IO.dll
----------------------------------------
System.Text.Encoding
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Text.Encoding/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Text.Encoding.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Extensions.dll
----------------------------------------
System.Threading
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll
----------------------------------------
System.Collections
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
System.Globalization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Globalization/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Globalization.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Semantics
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/Semantics.DLL
----------------------------------------
Microsoft.Msagl.GraphViewerGdi
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/Microsoft.Msagl.GraphViewerGdi.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.Msagl.Drawing
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/Microsoft.Msagl.Drawing.DLL
----------------------------------------
Microsoft.Msagl
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/Bent%20Rasmussen/Documents/Repositories/statical.prism4al/Prism/Prism/bin/Debug/Microsoft.Msagl.DLL
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
PresentationFramework-SystemData
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4018.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by bent-rasmussen** [comment]
I see GViewer inside WPF is not a supported scenario. So closing this issue again. Still, would be nice if fixed.
