### ISSUE TITLE
Could not load file or assembly 'Microsoft.VisualStudio.Diagnostics.PerformanceProvider, Version=17.0.0.0, Culture=neutral,

### ISSUE THREAD

**Issue by shankargururajaamat** [microsoft/automatic-graph-layout#378]
Getting below exception when i try to run the samples/LoadingDgmlGraph , how can resolve this. tried running in vs 2017 and 2022 as well. but same error

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Microsoft.VisualStudio.Diagnostics.PerformanceProvider, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Source=Microsoft.VisualStudio.GraphModel
  StackTrace:
   at Microsoft.VisualStudio.GraphModel.Graph.GraphTransactionEnlistment_BeforeUpdate(GraphTransactionEnlistmentEventArgs evt)
   at Microsoft.VisualStudio.GraphModel.GraphTransactionEnlistment.FireGraphPrepareListeners(GraphTransactionEnlistmentEventArgs args)
   at Microsoft.VisualStudio.GraphModel.GraphTransactionEnlistment.System.Transactions.IEnlistmentNotification.Prepare(PreparingEnlistment preparingEnlistment)
   at System.Transactions.VolatileEnlistmentPreparing.EnterState(InternalEnlistment enlistment)
   at System.Transactions.VolatileEnlistmentActive.ChangeStatePreparing(InternalEnlistment enlistment)
   at System.Transactions.TransactionStateVolatilePhase1.EnterState(InternalTransaction tx)
   at System.Transactions.TransactionStatePhase0.EnterState(InternalTransaction tx)
   at System.Transactions.TransactionStateActive.BeginCommit(InternalTransaction tx, Boolean asyncCommit, AsyncCallback asyncCallback, Object asyncState)
   at System.Transactions.CommittableTransaction.Commit()
   at System.Transactions.TransactionScope.InternalDispose()
   at System.Transactions.TransactionScope.Dispose()
   at Microsoft.VisualStudio.GraphModel.GraphTransactionScope.Dispose(Boolean disposing)
   at Microsoft.VisualStudio.GraphModel.GraphTransactionScope.Dispose()
   at Microsoft.VisualStudio.GraphModel.TransactedPropertyList`1.SetValue(GraphProperty property, Graph metadataGraph, T value)
   at Microsoft.VisualStudio.GraphModel.GraphObject.SetValue(GraphProperty property, Type type, Object value)
   at Microsoft.VisualStudio.GraphModel.GraphObject.SetValue[T](GraphProperty property, T value)
   at Microsoft.VisualStudio.GraphModel.GraphSerializer.Deserialize(XDocument doc, String baseUri)
   at Microsoft.VisualStudio.GraphModel.GraphSerializer.LoadFromXmlReader(XmlReader reader, EventHandler`1 progressHandler, GraphSchema[] schemas)
   at Microsoft.VisualStudio.GraphModel.GraphSerializer.Load(String fileName, EventHandler`1 progressHandler, GraphSchema[] schemas)
   at Microsoft.VisualStudio.GraphModel.Graph.Load(String fileName, EventHandler`1 progressHandler, GraphSchema[] schemas)
   at DgmlParser.DgmlParser.Parse(String filename) in C:

**Comment by levnach** [comment]
It is fixed
